/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package trashsort;

import org.junit.jupiter.api.Test;

class TrashTest {
    @Test void Difficulty() {
        assert(Tools.matchDifficultyText("normal") == 1);
    }
}
